### ISSUE TITLE
How to pass create_by and remote_addr parameter?

### ISSUE THREAD

**Issue by rockers007** [itelmenko/laravel-mysql-logger#2]
How to pass create_by and remote_addr parameter?

**Comment by itelmenko** [comment]
Hi @rockers007 ! I think `remote_addr` and another is contextual information. Like `id` in [documentation ](https://laravel.com/docs/5.6/logging). 

```php
Log::info('User failed to login.', ['id' => $user->id]);
```

Did you try it?

**Comment by rockers007** [comment]
@itelmenko  Thanks ,but its not working,I already tried for this

**Comment by itelmenko** [comment]
@rockers007 
```php
Log::info('Something happened!', ['remote_addr' => '127.0.0.2']);
```
It works for me. Tried in artisan tinker.
In database I see this parameter in context field
