### ISSUE TITLE
Bug: Using env() in the create_logs_table migration. config() should be used instead

### ISSUE THREAD

**Issue by bdteo** [itelmenko/laravel-mysql-logger#4]
https://stackoverflow.com/questions/40026893/what-is-difference-between-use-envapp-env-configapp-env-or-appenviron

**Comment by bdteo** [comment]
The worst thing are actually these lines of code
   ```
 public function __construct(array $attributes = array())
    {
        $this->table      = env('DB_LOG_TABLE', 'logs');
        $this->connection = env('DB_LOG_CONNECTION', env('DB_CONNECTION', 'mysql'));

        parent::__construct($attributes);
    }
```
They render the package absolutely unusable in production.

**Comment by itelmenko** [comment]
Hello! Do you think I need add a separated configuration file?
Without configuration file I can not use `config()`

**Comment by itelmenko** [comment]
Thank you @bdteo for comments! Fixed
