### ISSUE TITLE
Not enough information is stored in the "message" column

### ISSUE THREAD

**Issue by matthewborgcarr** [itelmenko/laravel-mysql-logger#5]
Is it possible to enhance the error message information stored in the message column in the database.

In my case, when a particular error occurred the message saved in the database states: "trying to get property of non object".

It would be ideal if this message included also the file this error occured in or the controller that is generating the error... anyway any further information that may help developers troubleshoot and fix any issues.

I hope this is clear enough.

Looking forward to hearing from you.

Matthew

**Comment by itelmenko** [comment]
Hi @matthewborgcarr !
Please, try version 0.1.11 and see in "context" field for details of exception. Array "trace"
