### ISSUE TITLE
PHP Fatal Error with Laravel 6

### ISSUE THREAD

**Issue by awdhir** [itelmenko/laravel-mysql-logger#6]
Hello, 

I just updated to Larevel 6.0 (from 5.8) and when I run "php artisan serve", I get the follow message error:

PHP Fatal error:  Declaration of Logger\Monolog\Handler\MysqlHandler::write(array $record) must be compatible with Monolog\Handler\AbstractProcessingHandler::write(array $record): void in myproject\array $record): void in myproject\SiMeliusv3\vendor\itelmenko\laravel-mysql-logger\src\Logger\Monolog\Handler\MysqlHandler.php on line 11

I saw that Monolog versión was updated from 1.12 to 2.0 in Laravel 6.

Could you check pls? 
Thk'u very much 4 your time (& sorry by my poor english)
Regards

**Comment by awdhir** [comment]
Hi again.

I resolved the error, adding `:void` in your "write" method (inside MysqlHandler.php)
Now, looks like this:

```
class MysqlHandler extends AbstractProcessingHandler
{
    protected function write(array $record) :void
    {
        Log::create([
            'instance'    => gethostname(),
            'channel'     => $record['channel'],
            'message' => $record['message'],
            'level'   => $record['level_name'],
            'context' => $record['context']
        ]);
    }
}
```
Thk'u again, your package is very helpful 4me.

**Comment by itelmenko** [comment]
Thank you @awdhir , thank you @JarvisHo 
Merged and updated
