### ISSUE TITLE
Change env by config in MySQLLogger

### ISSUE THREAD

**Issue by luishenriqueamaral** [itelmenko/laravel-mysql-logger#8]
Hi Igor

First of all, thanks for the great package.

I would like to suggest a change, at:

https://github.com/itelmenko/laravel-mysql-logger/blob/824b16660b65f673489a63a799f26c7044834af1/src/Logger/Laravel/Logging/MySQLLogger.php#L20

To:

`$channel = $config['name'] ?? config('app.env');`

This is because when config:cache is executed, env's variables are no longer accessible, as per this [doc](https://laravel.com/docs/7.x/configuration#configuration-caching).

Thanks

**Comment by itelmenko** [comment]
@luishenriqueamaral Thank you for the fix. I have updated repo in commit 9a15432f912c634b5ec0a969e0975349985a879d

**Comment by luishenriqueamaral** [comment]
Thanks @itelmenko !
